### ISSUE TITLE
Is there a timestamp conversion with milliseconds

### ISSUE THREAD

**Issue by xxdoc** [OlimilO1402/Date_TimeConversion#1]
1679881227842-----------2023-03-27 09:40:27:842       ---YYYY-MM-DD HH:mm:ss:SSS
1679881268      -----------2023-03-27 09:41:08---------YYYY-MM-DD HH:mm:ss

**Comment by OlimilO1402** [comment]
Hi, thanks for the idea, unfortunately the resolution of TimeStamp in a Long (Int32) is just 1 second. le's say we have:
```vba
Dim dts As Long: dts = 1679881268
MsgBox MTime.DateTimeStamp_ToStr(dts)
'now we increase by 1:
dts = dts + 1
MsgBox MTime.DateTimeStamp_ToStr(dts) 'just 1 second more, no place for milliseconds
```
